# Generated by Django 3.1.3 on 2020-11-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_auto_20201121_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
