# Generated by Django 3.1.3 on 2020-12-19 00:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='imagen',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
