# Generated by Django 3.1.3 on 2020-11-29 23:16

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(blank=True, default=chat.models.generate_random_code, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
