# Generated by Django 3.1.3 on 2020-12-07 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_room_current_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='current_users',
        ),
        migrations.AddField(
            model_name='room',
            name='current_users',
            field=models.ManyToManyField(related_name='current_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
